updated src duplicate-char, main, palindrome, rotation
NitinSaxenait/RUST_ASSIGNMENT pull request #8
Opened 2021-03-08 11:44 UTC by NitinSaxenait

Please use this PR template
What does this change do?
feature added of complex number and student operations
Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
No, only for the mentor.

Definition of Done:

Is there >80% unit test code coverage?
if not please mention the Code Coverage of code.

Does this PR add new dependencies? If so, please list out the same.
No

Will this feature require a new piece of infrastructure to be implemented?
Is there appropriate logging included?
yes
Does the project compile ok?
yes

Have Clippy violations been fixed?
yes

Have Code is properly formatted?
yes

2021-03-08 11:57 UTC, Dheerajjnv submitted a review, later dismissed

2021-03-08 12:01 UTC, Dheerajjnv approved these changes
Use log.

2021-03-08 12:05 UTC, sonukumar-a11 approved these changes
Please Write comment in more expressive way.

2021-03-08 14:05 UTC, ksr30 requested changes

2021-03-08 14:05 UTC, ksr30 commented on Assignment4/src/duplicate_character_string.rs
> +// a string is taken as a parameter to verify whether it has duplicate char or not
redo

2021-03-08 14:05 UTC, ksr30 commented on Assignment4/src/rotation_string.rs
> +pub fn reverse_is_true(input1_string: &str, input2_string: &str) -> String {
redo

2021-03-14 06:41 UTC, NitinSaxenait commented on Assignment4/src/duplicate_character_string.rs
> +// a string is taken as a parameter to verify whether it has duplicate char or not
Done

2021-03-14 06:41 UTC, NitinSaxenait commented on Assignment4/src/rotation_string.rs
> +pub fn reverse_is_true(input1_string: &str, input2_string: &str) -> String {
Done

2021-03-14 06:46 UTC, closed without merging